#requires -version 5
<#
.SYNOPSIS
  Checks which services can be disabled on your corporate system (Windows Server 2016) environment. Best practices prepared by Microsoft.

.DESCRIPTION
  This script gets security guideline information from github page:
    https://raw.githubusercontent.com/leoleg/Win-ServicesGuidelineChecker/main/service_security_guideline.csv 
  After that script checks whether services running on your system is matching Windows Security Guideline. 
  This csv file is generated by python script that parses information from Microsoft Windows Server 2016 guideline page;
    https://docs.microsoft.com/en-us/windows-server/security/windows-services/security-guidelines-for-disabling-system-services-in-windows-server

.INPUTS
  You can create your own service_security_guideline.csv file (or modify existing) to create your own best practices.
.OUTPUTS
  service_security_guideline.csv

.NOTES
  Version:        1.0
  Author:         LeOleg
  Creation Date:  31.01.2020  
#>


$service_guideline_file = "service_security_guideline.csv"
$security_guideline_csv_link = "https://raw.githubusercontent.com/leoleg/Win-ServicesGuidelineChecker/main/service_security_guideline.csv"

if (! Test-Path $service_guideline_file)
{
    Invoke-WebRequest $security_guideline_csv_link | Select-Object -ExpandProperty Content | Out-File $service_guideline_file
}

$services_guideline=Import-CSV -Path "service_security_guideline.csv"

$service_list = $services_guideline | Where-Object { $_.Recommendation -notin "Do not disable", "No guidance"}

foreach ($service in $service_list)
{
    $service_name=Get-Service -Name $service.'Service name'
    if ($service_name.Status -ne "Stopped")
    {
        Write-Host("Service " + $service_name.Name + " is enabled. Due to security guideline this service recommended to be disabled.") -fore red
    }
}
